[registry_hosts]
#Liste des IPs (une par ligne)
13.60.38.86

[registry_hosts:vars]
#variable communes à tous les hôtes du groupe
ansible_user=ubuntu
ansible_ssh_private_key_file=registry-key.pem
#on désaction la vérification de la clé hôte pour éviter le prompt
ansible_ssh_common_args='-o StrictHostKeyChecking=no'