---
- name : Déploiement d'un server en production
  hosts: all
  become: true
  vars :
    project_dir : /home/ubuntu/my-app
    docker_username : "{{ github_user }}"
    docker_password : "{{ github_token }}"
    registry_url : "ghcr.io"
  tasks:

    - name: Mise à jour du cache APT
      apt:
        update_cache: yes

    - name: Installation de Docker
      apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present

    - name: Ajout de l'utilisateur ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name : Démarrage de Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Création des dossiers
      file:
        path: "{{ project_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Connexion au registry Docker
      community.docker.docker_login:
        registry_url: "{{ registry_url }}"
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Copie du docker-compose.yml
      template:
        src: docker-compose-prod.yml
        dest: "{{ project_dir }}/docker-compose.yml" ## voir le nom du fichier
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Démarrage de la stack Docker
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        state: present
